require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

# RSpec/ExampleLength:
#   Max: 10

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120
RSpec/FilePath:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
  